// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "apiBaseUrl": string;
      "model": string;
      "autoSaveStructuredOutput": boolean;
      "defaultTemplate": string;
      "temperature": string;
      "topP": string;
      "topK": string;
      "maxOutputTokens": string;
      "enableTagSync": boolean;
      "tagLanguage": string;
    };
  }
}
